@startuml

top to bottom direction

package BusinessLayer {
    class Bot   
    class FreeBot
    class PremiumBot
    FreeBot -|> Bot
    PremiumBot -|> Bot

    class ViberFreeBot {}
    ViberFreeBot -|> FreeBot
    ViberPremiumBot -|> PremiumBot

    class Crawler {}

    class XSMB_Crawler {}
    XSMB_Crawler -|> Crawler 

    class CrawlStrategy {}

    class XSMB_Crawl_Strategy {}

    class XSMB_Crawler_KetQua_VN {}
    XSMB_Crawler_KetQua_VN -|> XSMB_Crawl_Strategy
    XSMB_Crawl_Strategy -|> CrawlStrategy

    
    XSMB_Crawl_Strategy --* XSMB_Crawler

}


package Model_Layer {

    class BotSubcriber {
        name:str 
        uid:str
        subscription_type:SubscriptionChoices
    }

    class BotModel {

    }

    Bot .. BotModel: save data to 
    BotSubcriber .. BotModel: use 

    class Notification {
        message: str 
    }

    class XoSoMienBac {}

    XSMB_Crawl_Strategy --> XoSoMienBac: create 

    class XSMB_So_Dep {}

    class XMSB_Number_Statistic {}

    class BotUsage {}

    BotModel .. BotUsage 
    BotSubcriber .. BotUsage

}

@enduml