# Generated by Django 3.2.13 on 2022-05-18 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='BotSubcriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('avatar', models.TextField(default='')),
                ('uid', models.TextField(default='')),
                ('subcription_type', models.IntegerField(choices=[(1, 'Free User'), (2, 'Premium User')], default=1)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bots.botmodel')),
            ],
        ),
    ]
