# Generated by Django 3.2.13 on 2022-05-18 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botsubcriber',
            old_name='subcription_type',
            new_name='subscription_type',
        ),
    ]
