# Generated by Django 3.2.13 on 2022-05-18 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_rename_subcription_type_botsubcriber_subscription_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsubcriber',
            name='user_provided_name',
            field=models.TextField(default=''),
        ),
    ]
