# Generated by Django 3.2.13 on 2022-05-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_botsubcriber_user_provided_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsubcriber',
            name='has_subcribed',
            field=models.BooleanField(default=False),
        ),
    ]
