# Generated by Django 3.2.13 on 2022-05-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_botsubcriber_has_subcribed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Nội dung')),
            ],
        ),
    ]
