# Generated by Django 3.2.13 on 2022-05-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmodel',
            name='auth_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='botmodel',
            name='bot_type',
            field=models.IntegerField(choices=[(1, 'Free Bot'), (2, 'Premium Bot')], default=1),
        ),
        migrations.AlterField(
            model_name='botmodel',
            name='name',
            field=models.TextField(blank=True, default=''),
        ),
    ]
