# Generated by Django 3.2.13 on 2022-05-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0006_auto_20220524_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botmodel',
            name='bot_type',
            field=models.IntegerField(choices=[(1, 'Free Bot'), (2, 'Premium Bot'), (3, 'Test Bot')], default=1),
        ),
    ]
