# Generated by Django 3.2.13 on 2022-05-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0007_alter_botmodel_bot_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botmodel',
            name='bot_type',
            field=models.IntegerField(choices=[(1, 'Free Bot'), (2, 'Premium Bot'), (3, 'Free Test Bot'), (4, 'Premium Test Bot')], default=1),
        ),
    ]
