# Generated by Django 3.2.13 on 2022-05-24 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0008_alter_botmodel_bot_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botsubcriber',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcribers', to='bots.botmodel'),
        ),
    ]
