# Generated by Django 3.2.13 on 2022-05-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0009_alter_botsubcriber_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsubcriber',
            name='feature_session',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='botsubcriber',
            name='feature_step',
            field=models.TextField(default=''),
        ),
    ]
