# Generated by Django 3.2.13 on 2022-06-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0011_botsubcriber_feature_args'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botsubcriber',
            name='avatar',
            field=models.TextField(default='', null=True),
        ),
    ]
