# Generated by Django 3.2.13 on 2022-06-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0012_alter_botsubcriber_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsubcriber',
            name='unlocked_features',
            field=models.JSONField(blank=True, null=True, verbose_name='Mở khóa tính năng'),
        ),
    ]
