# Generated by Django 3.2.13 on 2022-06-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0013_botsubcriber_unlocked_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsubcriber',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
