# Generated by Django 3.2.13 on 2022-06-04 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0014_botsubcriber_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botmodel',
            options={'verbose_name': 'Quản lý bot'},
        ),
        migrations.AlterModelOptions(
            name='botsubcriber',
            options={'verbose_name': 'Quản lý Subcribers'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Quản lý thông báo'},
        ),
    ]
