# Generated by Django 3.2.13 on 2022-06-04 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0015_auto_20220604_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('bot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bots.botmodel')),
                ('subcriber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bots.botsubcriber')),
            ],
        ),
    ]
