# Generated by Django 3.2.13 on 2022-06-04 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0016_botusage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botusage',
            options={'verbose_name': 'Thống kê sử dụng'},
        ),
    ]
