# Generated by Django 3.2.13 on 2022-09-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render_image', '0002_auto_20220925_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendertemplate',
            name='guidance_scale',
            field=models.FloatField(default=7.5),
        ),
        migrations.AlterField(
            model_name='rendertemplate',
            name='num_inference_steps',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='rendertemplate',
            name='prompt_strength',
            field=models.FloatField(default=0.8),
        ),
    ]
