# Generated by Django 3.2.13 on 2022-09-24 21:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render_image', '0005_rendertransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendertransaction',
            name='image_urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), null=True, size=None),
        ),
    ]
