# Generated by Django 3.2.13 on 2022-09-24 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('render_image', '0006_alter_rendertransaction_image_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendertransaction',
            name='render_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='render_image.rendertemplate'),
        ),
    ]
