#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python3 /app/manage.py collectstatic --noinput
python3 /app/manage.py makemigrations render_image
python3 /app/manage.py makemigrations users
python3 /app/manage.py migrate
/usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app --log-level=DEBUG
