# Generated by Django 3.2.13 on 2022-09-26 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_bill_notification_pocket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='has_sent',
        ),
    ]
