# Generated by Django 3.2.13 on 2022-05-18 07:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XoSoMienBac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('giai_dac_biet', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=''), size=None)),
                ('giai_nhat', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=''), size=None)),
                ('giai_nhi', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=''), size=None)),
                ('giai_ba', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=''), size=None)),
                ('giai_tu', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=''), size=None)),
                ('giai_nam', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=''), size=None)),
                ('giai_sau', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=''), size=None)),
                ('giai_bay', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=''), size=None)),
                ('dau_lo_to', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=''), size=None), size=10)),
                ('duoi_lo_to', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=''), size=None), size=10)),
            ],
        ),
    ]
