# Generated by Django 3.2.13 on 2022-05-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kq_xo_so', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xosomienbac',
            name='date',
            field=models.DateField(),
        ),
    ]
