# Generated by Django 3.2.13 on 2022-05-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kq_xo_so', '0002_alter_xosomienbac_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xosomienbac',
            name='date',
        ),
        migrations.AddField(
            model_name='xosomienbac',
            name='Ngày',
            field=models.DateField(null=True),
        ),
    ]
