# Generated by Django 3.2.13 on 2022-05-18 08:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kq_xo_so', '0003_auto_20220518_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xosomienbac',
            name='dau_lo_to',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, default=''), size=None), size=10),
        ),
        migrations.AlterField(
            model_name='xosomienbac',
            name='duoi_lo_to',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, default=''), size=None), size=10),
        ),
        migrations.AlterField(
            model_name='xosomienbac',
            name='giai_ba',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, default=''), size=None),
        ),
        migrations.AlterField(
            model_name='xosomienbac',
            name='giai_bay',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, default=''), size=None),
        ),
        migrations.AlterField(
            model_name='xosomienbac',
            name='giai_dac_biet',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, default=''), size=None),
        ),
        migrations.AlterField(
            model_name='xosomienbac',
            name='giai_nam',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, default=''), size=None),
        ),
        migrations.AlterField(
            model_name='xosomienbac',
            name='giai_nhat',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, default=''), size=None),
        ),
        migrations.AlterField(
            model_name='xosomienbac',
            name='giai_nhi',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, default=''), size=None),
        ),
        migrations.AlterField(
            model_name='xosomienbac',
            name='giai_sau',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, default=''), size=None),
        ),
        migrations.AlterField(
            model_name='xosomienbac',
            name='giai_tu',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, default=''), size=None),
        ),
    ]
