# Generated by Django 3.2.13 on 2022-05-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kq_xo_so', '0004_auto_20220518_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xosomienbac',
            name='Ngày',
            field=models.DateField(),
        ),
    ]
