# Generated by Django 3.2.13 on 2022-05-18 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kq_xo_so', '0005_alter_xosomienbac_ngày'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xosomienbac',
            old_name='Ngày',
            new_name='ngay_trao_giai',
        ),
    ]
