# Generated by Django 3.2.13 on 2022-05-18 08:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kq_xo_so', '0006_rename_ngày_xosomienbac_ngay_trao_giai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xosomienbac',
            name='dau_lo_to',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, default='', verbose_name='Đầu lô tô'), size=None), size=10),
        ),
        migrations.AlterField(
            model_name='xosomienbac',
            name='duoi_lo_to',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, default='', verbose_name='Đuôi lô tô'), size=None), size=10),
        ),
        migrations.AlterField(
            model_name='xosomienbac',
            name='giai_ba',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, default='', verbose_name='Giải ba'), size=None),
        ),
        migrations.AlterField(
            model_name='xosomienbac',
            name='giai_bay',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, default='', verbose_name='Giải bảy'), size=None),
        ),
        migrations.AlterField(
            model_name='xosomienbac',
            name='giai_dac_biet',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, default='', verbose_name='Giải đặc biệt'), size=None),
        ),
        migrations.AlterField(
            model_name='xosomienbac',
            name='giai_nam',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, default='', verbose_name='Giải năm'), size=None),
        ),
        migrations.AlterField(
            model_name='xosomienbac',
            name='giai_nhat',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, default='', verbose_name='Giải nhất'), size=None),
        ),
        migrations.AlterField(
            model_name='xosomienbac',
            name='giai_nhi',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, default='', verbose_name='Giải nhì'), size=None),
        ),
        migrations.AlterField(
            model_name='xosomienbac',
            name='giai_sau',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, default='', verbose_name='Giải sáu'), size=None),
        ),
        migrations.AlterField(
            model_name='xosomienbac',
            name='giai_tu',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, default='', verbose_name='Giải tư'), size=None),
        ),
        migrations.AlterField(
            model_name='xosomienbac',
            name='ngay_trao_giai',
            field=models.DateField(verbose_name='Ngày trao giải'),
        ),
    ]
