# Generated by Django 3.2.13 on 2022-05-18 08:44

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kq_xo_so', '0008_auto_20220518_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xosomienbac',
            name='dau_lo_to',
        ),
        migrations.RemoveField(
            model_name='xosomienbac',
            name='duoi_lo_to',
        ),
        migrations.AddField(
            model_name='xosomienbac',
            name='dau_lo_to_dau0',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(blank=True, default=[], verbose_name='Đầu lô tô đầu 0'), default=[], size=None),
        ),
        migrations.AddField(
            model_name='xosomienbac',
            name='dau_lo_to_dau1',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(blank=True, default=[], verbose_name='Đầu lô tô đầu 1'), default=[], size=None),
        ),
        migrations.AddField(
            model_name='xosomienbac',
            name='dau_lo_to_dau2',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(blank=True, default=[], verbose_name='Đầu lô tô đầu 2'), default=[], size=None),
        ),
        migrations.AddField(
            model_name='xosomienbac',
            name='dau_lo_to_dau3',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(blank=True, default=[], verbose_name='Đầu lô tô đầu 3'), default=[], size=None),
        ),
        migrations.AddField(
            model_name='xosomienbac',
            name='dau_lo_to_dau4',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(blank=True, default=[], verbose_name='Đầu lô tô đầu 4'), default=[], size=None),
        ),
        migrations.AddField(
            model_name='xosomienbac',
            name='dau_lo_to_dau5',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(blank=True, default=[], verbose_name='Đầu lô tô đầu 5'), default=[], size=None),
        ),
        migrations.AddField(
            model_name='xosomienbac',
            name='dau_lo_to_dau6',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(blank=True, default='', verbose_name='Đầu lô tô đầu 6'), default=[], size=None),
        ),
        migrations.AddField(
            model_name='xosomienbac',
            name='dau_lo_to_dau7',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(blank=True, default='', verbose_name='Đầu lô tô đầu 7'), default=[], size=None),
        ),
        migrations.AddField(
            model_name='xosomienbac',
            name='dau_lo_to_dau8',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(blank=True, default='', verbose_name='Đầu lô tô đầu 8'), default=[], size=None),
        ),
        migrations.AddField(
            model_name='xosomienbac',
            name='dau_lo_to_dau9',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(blank=True, default='', verbose_name='Đầu lô tô đầu 9'), default=[], size=None),
        ),
        migrations.AddField(
            model_name='xosomienbac',
            name='duoi_lo_to_dau0',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(blank=True, default='', verbose_name='Đuôi lô tô đầu 0'), default=[], size=None),
        ),
        migrations.AddField(
            model_name='xosomienbac',
            name='duoi_lo_to_dau1',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(blank=True, default='', verbose_name='Đuôi lô tô đầu 1'), default=[], size=None),
        ),
        migrations.AddField(
            model_name='xosomienbac',
            name='duoi_lo_to_dau2',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(blank=True, default='', verbose_name='Đuôi lô tô đầu 2'), default=[], size=None),
        ),
        migrations.AddField(
            model_name='xosomienbac',
            name='duoi_lo_to_dau3',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(blank=True, default='', verbose_name='Đuôi lô tô đầu 3'), default=[], size=None),
        ),
        migrations.AddField(
            model_name='xosomienbac',
            name='duoi_lo_to_dau4',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(blank=True, default='', verbose_name='Đuôi lô tô đầu 4'), default=[], size=None),
        ),
        migrations.AddField(
            model_name='xosomienbac',
            name='duoi_lo_to_dau5',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(blank=True, default='', verbose_name='Đuôi lô tô đầu 5'), default=[], size=None),
        ),
        migrations.AddField(
            model_name='xosomienbac',
            name='duoi_lo_to_dau6',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(blank=True, default='', verbose_name='Đuôi lô tô đầu 6'), default=[], size=None),
        ),
        migrations.AddField(
            model_name='xosomienbac',
            name='duoi_lo_to_dau7',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(blank=True, default='', verbose_name='Đuôi lô tô đầu 7'), default=[], size=None),
        ),
        migrations.AddField(
            model_name='xosomienbac',
            name='duoi_lo_to_dau8',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(blank=True, default='', verbose_name='Đuôi lô tô đầu 8'), default=[], size=None),
        ),
        migrations.AddField(
            model_name='xosomienbac',
            name='duoi_lo_to_dau9',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(blank=True, default='', verbose_name='Đuôi lô tô đầu 9'), default=[], size=None),
        ),
    ]
