# Generated by Django 3.2.13 on 2022-05-18 08:46

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kq_xo_so', '0010_auto_20220518_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xosomienbac',
            name='duoi_lo_to_dau5',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(blank=True, default='', verbose_name='Đuôi lô tô đầu 5'), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='xosomienbac',
            name='duoi_lo_to_dau6',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(blank=True, default='', verbose_name='Đuôi lô tô đầu 6'), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='xosomienbac',
            name='duoi_lo_to_dau7',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(blank=True, default='', verbose_name='Đuôi lô tô đầu 7'), default=list, size=None),
        ),
    ]
