# Generated by Django 3.2.13 on 2022-05-24 11:30

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kq_xo_so', '0015_auto_20220524_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='xosomienbac',
            name='ket_qua_kep',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(blank=True, default='', verbose_name='Kép'), null=True, size=None),
        ),
    ]
