# Generated by Django 3.2.13 on 2022-05-29 12:18

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kq_xo_so', '0016_xosomienbac_ket_qua_kep'),
    ]

    operations = [
        migrations.CreateModel(
            name='XSMB_So_Dep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dau_duoi_giai_dac_biet', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(blank=True, default='', verbose_name='Đầu đuôi đặc biệt'), size=None)),
                ('lo_to_kep', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(blank=True, default='', verbose_name='Lô tô kép'), size=None)),
                ('dau_cam', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(blank=True, default='', verbose_name='Đầu câm hôm qua'), size=None)),
                ('duoi_cam', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(blank=True, default='', verbose_name='Đuôi câm hôm qua'), size=None)),
            ],
        ),
    ]
