# Generated by Django 3.2.13 on 2022-05-29 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kq_xo_so', '0017_xsmb_so_dep'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xsmb_so_dep',
            old_name='dau_cam',
            new_name='dau_cam_hom_qua',
        ),
        migrations.RenameField(
            model_name='xsmb_so_dep',
            old_name='duoi_cam',
            new_name='duoi_cam_hom_qua',
        ),
        migrations.AddField(
            model_name='xsmb_so_dep',
            name='ngay',
            field=models.DateField(default=datetime.date(2022, 5, 29), verbose_name='Ngày trao giải'),
            preserve_default=False,
        ),
    ]
