# Generated by Django 3.2.13 on 2022-05-29 16:43

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kq_xo_so', '0018_auto_20220529_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='xsmb_so_dep',
            name='dau_cam_dep',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(blank=True, default='', verbose_name='Đầu câm đẹp'), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xsmb_so_dep',
            name='duoi_cam_dep',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(blank=True, default='', verbose_name='Đuôi câm đẹp'), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xsmb_so_dep',
            name='so_dep_dau_cam',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(blank=True, default='', verbose_name='Số đẹp đầu câm'), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xsmb_so_dep',
            name='so_dep_duoi_cam',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(blank=True, default='', verbose_name='Số đẹp đuôi câm'), default=[], size=None),
            preserve_default=False,
        ),
    ]
