# Generated by Django 3.2.13 on 2022-05-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kq_xo_so', '0019_auto_20220529_1643'),
    ]

    operations = [
    ]
