# Generated by Django 3.2.13 on 2022-05-29 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kq_xo_so', '0020_auto_20220529_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xsmb_so_dep',
            name='dau_cam_dep',
        ),
        migrations.RemoveField(
            model_name='xsmb_so_dep',
            name='duoi_cam_dep',
        ),
    ]
