# Generated by Django 3.2.13 on 2022-05-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kq_xo_so', '0021_auto_20220529_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='xsmb_so_dep',
            name='dau_cam_dep',
            field=models.JSONField(blank=True, null=True, verbose_name='Đầu câm đẹp'),
        ),
        migrations.AddField(
            model_name='xsmb_so_dep',
            name='duoi_cam_dep',
            field=models.JSONField(blank=True, null=True, verbose_name='Đuôi câm đẹp'),
        ),
    ]
