# Generated by Django 3.2.13 on 2022-05-29 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kq_xo_so', '0022_auto_20220529_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xsmb_so_dep',
            name='so_dep_dau_cam',
        ),
        migrations.RemoveField(
            model_name='xsmb_so_dep',
            name='so_dep_duoi_cam',
        ),
    ]
