# Generated by Django 3.2.13 on 2022-05-31 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kq_xo_so', '0023_auto_20220529_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='XSMB_Number_Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(verbose_name='Từ ngày')),
                ('to_date', models.DateField(verbose_name='Tới ngày')),
                ('number', models.IntegerField(default=0, verbose_name='Số thống kê')),
                ('number_freq', models.IntegerField(default=0, verbose_name='Số lần xuất hiện')),
                ('occurrences', models.JSONField(blank=True, null=True, verbose_name='Xuất hiện')),
            ],
        ),
    ]
