# Generated by Django 3.2.13 on 2022-06-01 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kq_xo_so', '0024_xsmb_number_statistic'),
    ]

    operations = [
        migrations.CreateModel(
            name='XSMB_Quick_Statistic_Giai_Dac_Biet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay', models.DateField(verbose_name='Ngày thống kê')),
                ('hai_so_cuoi_30', models.JSONField(blank=True, null=True, verbose_name='Hai số cuối 30 ngày')),
                ('hai_so_cuoi_365', models.JSONField(blank=True, null=True, verbose_name='Hai số cuối 365 ngày')),
                ('dau_so_cuoi_365', models.JSONField(blank=True, null=True, verbose_name='Đầu hai số cuối 365 ngày')),
                ('duoi_so_cuoi_365', models.JSONField(blank=True, null=True, verbose_name='Đầu hai số cuối 365 ngày')),
                ('hai_so_cuoi_lau_ve_365', models.JSONField(blank=True, null=True, verbose_name='Hai số cuối lâu về 365 ngày')),
                ('giai_db_ve_nhieu_nhat_hom_sau', models.JSONField(blank=True, null=True, verbose_name='Giải đặc biệt về nhiều nhất hôm sau')),
            ],
        ),
        migrations.CreateModel(
            name='XSMB_Quick_Statistic_Loto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay', models.DateField(verbose_name='Ngày thống kê')),
                ('lo_to_nhieu_nhat', models.JSONField(blank=True, null=True, verbose_name='Lô tô nhiều nhất')),
                ('lo_to_it_nhat', models.JSONField(blank=True, null=True, verbose_name='Lô tô ít nhất')),
                ('lo_khan', models.JSONField(blank=True, null=True, verbose_name='Lô tô khan')),
                ('lo_roi', models.JSONField(blank=True, null=True, verbose_name='Lô rơi')),
                ('dau_so_freq', models.JSONField(blank=True, null=True, verbose_name='Đầu số')),
                ('duoi_so_freq', models.JSONField(blank=True, null=True, verbose_name='Đuôi số')),
                ('lo_to_ve_nhieu_giai_dac_biet', models.JSONField(blank=True, null=True, verbose_name='Lô tô về nhiều')),
                ('lo_to_ve_nhieu_dau_cam', models.JSONField(blank=True, null=True, verbose_name='Lô tô về nhiều đầu câm')),
            ],
        ),
    ]
