# Generated by Django 3.2.13 on 2022-06-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kq_xo_so', '0025_xsmb_quick_statistic_giai_dac_biet_xsmb_quick_statistic_loto'),
    ]

    operations = [
        migrations.AddField(
            model_name='xsmb_quick_statistic_loto',
            name='giai_dac_biet_hom_qua',
            field=models.TextField(blank=True, default='', verbose_name='Giải đặc biệt hôm qua'),
        ),
        migrations.AddField(
            model_name='xsmb_quick_statistic_loto',
            name='lo_to_ve_nhieu_duoi_cam',
            field=models.JSONField(blank=True, null=True, verbose_name='Lô tô về nhiều đuôi câm'),
        ),
    ]
