# Generated by Django 3.2.13 on 2022-06-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kq_xo_so', '0026_auto_20220601_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='xsmb_quick_statistic_giai_dac_biet',
            name='giai_db_hom_qua',
            field=models.TextField(blank=True, default='', verbose_name='Giải đặc biệt hôm qua'),
        ),
    ]
